os: Visual Studio 2015
version: '{branch}.0.{build}'
build_script:
  - build.cmd
clone_depth: 1
test: off
deploy: off
artifacts:
  - path: src/RestSharp.Newtonsoft.Json.NetCore\bin\Release\*.nupkg
    name: RestSharp.Newtonsoft.Json.NetCore